name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{ cookiecutter.python_version }}"
          cache: 'pip'
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
      
      - name: Install dependencies
        run: |
          uv pip install -e ".[dev,docs]"
      
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
      
      - name: Run tests
        run: |
          python -m pytest tests/ --cov=src/ --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{ cookiecutter.python_version }}"
          cache: 'pip'
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
      
      - name: Install dependencies
        run: |
          uv pip install -e ".[dev]"
      
      - name: Run mypy
        run: |
          mypy src/ tests/

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{ cookiecutter.python_version }}"
          cache: 'pip'
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
      
      - name: Install dependencies
        run: |
          uv pip install -e ".[docs]"
      
      - name: Build documentation
        run: |
          mkdocs build --strict
      
      - name: Deploy to GitHub Pages
        if: {% raw %}${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}{% endraw %}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: {% raw %}${{ github.token }}{% endraw %}
          publish_dir: ./site
